apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amq-streams-operator

resources:
  - ../../base

patchesJson6902:
  - target:
      kind: Subscription
      name: amq-streams
    patch: |-
      - op: replace
        path: /spec/template/spec/channel
        value: stable

patchesJson6902:
  - target:
      kind: Subscription
      name: amq-streams
    patch: |-
      - op: replace
        path: /spec/namespace
        value: amq-streams-operator

patchesJson6902:
  - target:
      kind: Subscription
      name: amq-streams
    patch: |-
      - op: replace
        path: /spec/name
        value: amq-streams

configMapGenerator:
  - name: amqstreams-versions
    envs:
    - operator.versions
