apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-streams-og
  namespace: amq-streams-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: 
  targetNamespaces:
    - amq-streams-operator
