apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-streams.openshift-operators: ""
  name: amq-streams
  namespace: amq-streams-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable
  config:
    env:
    - name: FIPS_MODE
      value: disabled
  installPlanApproval: Manual
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v2.3.0-1
